/*
 * UFPumpController.h
 *
 * Created: 11/5/2014 3:40:49 PM
 *  Author: user
 */ 


#ifndef UFPUMPCONTROLLER_H_
#define UFPUMPCONTROLLER_H_


typedef enum {
	
	CL_UF_STATE_IDLE,
	CL_UF_STATE_STARTED,
	CL_UF_STATE_STOPPED,
	CL_UF_STATE_PAUSED,
	CL_UF_STATE_COMPLETED,
	CL_UF_STATE_MAXSTATE,
	CL_ISO_UF_STATE_START
	
	
}cl_uf_states;
typedef enum {
	
	CL_UF_EVENT_NULL,
	CL_UF_EVENT_SET_UF_RATE,
	CL_UF_EVENT_START,
	CL_UF_EVENT_PAUSE,
	CL_UF_EVENT_STOP,
	CL_UF_EVENT_COMPLETED,
	CL_UF_EVENT_SECOND,
	CL_UF_EVENT_MAX_EVENT,
	CL_UF_EVENT_RESET,
	CL_ISO_UF_EVENT_START
}cl_uf_events;

typedef enum {
	
	CL_ISOUF_STATE_IDLE,
	CL_ISOUF_STATE_STARTED,
	CL_ISOUF_STATE_STOPPED,
	CL_ISOUF_STATE_PAUSED,
	CL_ISOUF_STATE_COMPLETED,
	CL_ISOUF_STATE_MAXSTATE,
	CL_ISOUF_STATE_START,
	CL_ISOUF_STATE_POST_COMPLETION
	
}cl_isouf_states;
typedef enum {
	
	EVENT_ISOUF_NULL_EVENT,
	EVENT_ISOUF_CLR_ALARM,
	EVENT_ISOUF_GET_DATA,
	EVENT_ISOUF_SET_DATA,
	EVENT_ISOUF_START_RINSE,
	EVENT_ISOUF_START_DIALYSIS,
	EVENT_ISOUF_DLSIS_TIMEOUT,
	EVENT_ISOUF_TICK_50MS,
	EVENT_ISOUF_TICK_500MS,
	EVENT_ISOUF_TICK_SECOND,
	EVENT_ISOUF_TICK_MINUTE,
	EVENT_ISOUF_TICK_HOUR,
	EVENT_ISOUF_ALARM,
	EVENT_ISOUF_ALERT,
	EVENT_ISOUF_START_RETURN,
	EVENT_ISOUF_STOP_RETURN,
	EVENT_ISOUF_COMMAND_SET_BLDPUMPRATE,
	EVENT_ISOUF_COMMAND_SET_BLDPMP_ON,
	EVENT_ISOUF_COMMAND_SET_BLDPMP_OFF,
	EVENT_ISOUF_HEP_RATE,
	EVENT_ISOUF_HEP_ON,
	EVENT_ISOUF_HEP_OFF,
	EVENT_ISOUF_START,
	EVENT_ISOUF_PAUSED,
	EVENT_ISOUF_STOP,
	EVENT_ISOUF_COMPLETED,
	EVENT_ISOUF_RESET
	
	
}cl_isouf_events;



#endif /* UFPUMPCONTROLLER_H_ */